theme: jekyll-theme-hacker
name: linuxthor
markdown: kramdown
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-feed
    - jekyll-paginate
paginate: 10
paginate_path: "/:num/"
kramdown:
    input: GFM
    syntax_highlighter: rouge
